version: '3'

services:
    redis:
        image: redis
        container_name: redis-container

    zprime:
        image: zprime:demo
        container_name: zprime
        depends_on:
          - redis
        ports:
            - 8080:8080
            - 8000:8000
        volumes:
            - d:/MyPrograms/Java/_spring/zprime-service/target:/data



