server:
    port: 8080

pythia:
    pythia-path: ${PYTHIA_PATH}
    model-dir: ${MODEL_DIR}
    pythia-runner: ${PYTHIA_RUNNER}

#TODO: figure out why I need this here and in bootstrap.yml
spring:
    profiles.active: dev
    devtools.remote.secret: mysecret
    application:
        name: testLatticeApp
    redis:
        host: redis
        port: 6379

ribbon:
    ServerListRefreshInterval: 1000

endpoints:
    health:
        sensitive: false
    restart:
        enabled: true
    shutdown:
        enabled: true

amazon:
    aws:
        accesskey: key
        secretkey: secret
    dynamodb:
        endpoint: http://localhost:8000/
        region: localhost
